-- Authoritative curriculum replacement from Pharmacology_and_Pathology_Reference.docx.
-- This migration replaces curriculum topic rows only; it does not modify questions, practicals, knowledge chunks, or attachments.
begin;

alter table public.curriculum_topics
  add column if not exists subtopics jsonb not null default '[]'::jsonb;
alter table public.curriculum_topics drop constraint if exists curriculum_topics_day_number_check;
alter table public.curriculum_topics add constraint curriculum_topics_day_number_check check (day_number between 1 and 20);

insert into public.curriculum_courses (slug, name, description, accent_color, display_order)
values
  ('anatomical-pathology', 'Anatomical Pathology', 'General, systemic, autopsy, forensic, and organ-system pathology.', '#F4A261', '1'),
  ('chemical-pathology', 'Chemical Pathology', 'Laboratory medicine, renal and liver chemistry, endocrine, metabolic, and clinical chemical pathology.', '#2A9D8F', '2'),
  ('haematology-immunology', 'Haematology / Immunology', 'Haematopoiesis, anaemias, haemostasis, malignancy, transfusion medicine, and clinical immunology.', '#457B9D', '3'),
  ('microbiology', 'Microbiology', 'Medical microbiology, bacteriology, mycology, parasitology, virology, infection control, and clinical syndromes.', '#7C3AED', '4'),
  ('pharmacology', 'Pharmacology', 'General and autonomic pharmacology, system pharmacology, CNS, toxicology, and chemotherapy.', '#E76F51', '5')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  accent_color = excluded.accent_color,
  display_order = excluded.display_order,
  updated_at = now();

-- Delete only the old curriculum topic rows. Course identities remain stable, and all question-bank data remains untouched.
delete from public.curriculum_topics;

insert into public.curriculum_topics (course_id, slug, title, day_number, day_title, order_index, subtopics)
select c.id, seed.slug, seed.title, seed.day_number, seed.day_title, seed.order_index, seed.subtopics::jsonb
from public.curriculum_courses c
join (values
  ('pharmacology', 'general-pharmacology-introduction-to-pharmacology', 'Introduction to Pharmacology', 1, 'General Pharmacology', 1, '["Definitions and scope (pharmacology, pharmacy, therapeutics, toxicology)","Sources and nomenclature of drugs","Essential/generic drug concepts"]'),
  ('pharmacology', 'general-pharmacology-pharmacokinetics', 'Pharmacokinetics', 1, 'General Pharmacology', 2, '["Drug absorption and bioavailability","Drug distribution and protein binding","Biotransformation/metabolism (Phase I and Phase II reactions)","Drug excretion (renal, biliary, other routes)","Kinetics of elimination (zero-order vs first-order), half-life, clearance"]'),
  ('pharmacology', 'general-pharmacology-routes-of-drug-administration', 'Routes of Drug Administration', 1, 'General Pharmacology', 3, '["Enteral routes","Parenteral routes","Other routes (topical, inhalational, transdermal)"]'),
  ('pharmacology', 'general-pharmacology-pharmacodynamics', 'Pharmacodynamics', 1, 'General Pharmacology', 4, '["Drug receptors and mechanisms of drug action","Dose-response relationships","Agonists, partial agonists, antagonists","Therapeutic index and margin of safety"]'),
  ('pharmacology', 'general-pharmacology-drug-interactions', 'Drug Interactions', 1, 'General Pharmacology', 5, '["Pharmacokinetic interactions","Pharmacodynamic interactions"]'),
  ('pharmacology', 'general-pharmacology-adverse-drug-reactions-and-drug-toxicity', 'Adverse Drug Reactions and Drug Toxicity', 1, 'General Pharmacology', 6, '["Types of adverse drug reactions","Drug allergy and idiosyncrasy","Drug tolerance and dependence"]'),
  ('pharmacology', 'general-pharmacology-factors-modifying-drug-action', 'Factors Modifying Drug Action', 1, 'General Pharmacology', 7, '["Age (paediatric and geriatric pharmacology)","Pregnancy and lactation","Genetic/pharmacogenetic factors","Disease states (hepatic and renal impairment)"]'),
  ('pharmacology', 'general-pharmacology-drug-development-trials-and-pharmacovigilance', 'Drug Development, Trials and Pharmacovigilance', 1, 'General Pharmacology', 8, '["Stages of drug development","Clinical trial phases","Pharmacovigilance and adverse event reporting"]'),
  ('pharmacology', 'general-pharmacology-prescription-writing-and-rational-drug-use', 'Prescription Writing and Rational Drug Use', 1, 'General Pharmacology', 9, '["Principles of rational prescribing","Essential elements of a prescription"]'),
  ('pharmacology', 'autonomic-nervous-system-pharmacology-overview-of-autonomic-nervous-system', 'Overview of Autonomic Nervous System', 2, 'Autonomic Nervous System Pharmacology', 1, '["Sympathetic and parasympathetic divisions","Neurotransmitters and receptor subtypes"]'),
  ('pharmacology', 'autonomic-nervous-system-pharmacology-cholinergic-pharmacology', 'Cholinergic Pharmacology', 2, 'Autonomic Nervous System Pharmacology', 2, '["Direct-acting cholinergic agonists","Indirect-acting agents (anticholinesterases)","Clinical uses and toxicity (organophosphate poisoning)"]'),
  ('pharmacology', 'autonomic-nervous-system-pharmacology-anticholinergic-antimuscarinic-drugs', 'Anticholinergic (Antimuscarinic) Drugs', 2, 'Autonomic Nervous System Pharmacology', 3, '["Mechanism of action","Clinical uses and adverse effects"]'),
  ('pharmacology', 'autonomic-nervous-system-pharmacology-ganglionic-stimulants-and-blockers', 'Ganglionic Stimulants and Blockers', 2, 'Autonomic Nervous System Pharmacology', 4, '["Mechanism of action","Clinical relevance"]'),
  ('pharmacology', 'autonomic-nervous-system-pharmacology-neuromuscular-blocking-agents', 'Neuromuscular Blocking Agents', 2, 'Autonomic Nervous System Pharmacology', 5, '["Depolarizing agents","Non-depolarizing agents"]'),
  ('pharmacology', 'autonomic-nervous-system-pharmacology-adrenergic-pharmacology', 'Adrenergic Pharmacology', 2, 'Autonomic Nervous System Pharmacology', 6, '["Direct-acting adrenergic agonists (alpha and beta)","Indirect and mixed-acting sympathomimetics","Clinical uses"]'),
  ('pharmacology', 'autonomic-nervous-system-pharmacology-adrenergic-antagonists', 'Adrenergic Antagonists', 2, 'Autonomic Nervous System Pharmacology', 7, '["Alpha-blockers","Beta-blockers (selective and non-selective)"]'),
  ('pharmacology', 'cardiovascular-pharmacology-antihypertensive-drugs', 'Antihypertensive Drugs', 3, 'Cardiovascular Pharmacology', 1, '["Diuretics","ACE inhibitors and ARBs","Calcium channel blockers","Beta-blockers","Centrally-acting agents and direct vasodilators"]'),
  ('pharmacology', 'cardiovascular-pharmacology-antianginal-drugs', 'Antianginal Drugs', 3, 'Cardiovascular Pharmacology', 2, '["Nitrates","Beta-blockers","Calcium channel blockers"]'),
  ('pharmacology', 'cardiovascular-pharmacology-antiarrhythmic-drugs', 'Antiarrhythmic Drugs', 3, 'Cardiovascular Pharmacology', 3, '["Class I (sodium channel blockers)","Class II (beta-blockers)","Class III (potassium channel blockers)","Class IV (calcium channel blockers)"]'),
  ('pharmacology', 'cardiovascular-pharmacology-drugs-used-in-heart-failure', 'Drugs Used in Heart Failure', 3, 'Cardiovascular Pharmacology', 4, '["Cardiac glycosides (digoxin)","Diuretics","ACE inhibitors/ARBs and beta-blockers","Other inotropes"]'),
  ('pharmacology', 'cardiovascular-pharmacology-antihyperlipidaemic-drugs', 'Antihyperlipidaemic Drugs', 3, 'Cardiovascular Pharmacology', 5, '["Statins (HMG-CoA reductase inhibitors)","Fibrates","Bile acid sequestrants","Other lipid-lowering agents"]'),
  ('pharmacology', 'renal-pharmacology-diuretics', 'Diuretics', 4, 'Renal Pharmacology', 1, '["Loop diuretics","Thiazide diuretics","Potassium-sparing diuretics","Osmotic diuretics","Carbonic anhydrase inhibitors","Mechanisms, indications and adverse effects"]'),
  ('pharmacology', 'gastrointestinal-pharmacology-anti-ulcer-drugs', 'Anti-ulcer Drugs', 5, 'Gastrointestinal Pharmacology', 1, '["H2-receptor antagonists","Proton pump inhibitors","Antacids","Mucosal protective agents"]'),
  ('pharmacology', 'gastrointestinal-pharmacology-antiemetics', 'Antiemetics', 5, 'Gastrointestinal Pharmacology', 2, '["Classification and mechanisms"]'),
  ('pharmacology', 'gastrointestinal-pharmacology-laxatives-and-antidiarrhoeal-agents', 'Laxatives and Antidiarrhoeal Agents', 5, 'Gastrointestinal Pharmacology', 3, '["Classification and mechanisms"]'),
  ('pharmacology', 'gastrointestinal-pharmacology-drugs-for-inflammatory-bowel-disease', 'Drugs for Inflammatory Bowel Disease', 5, 'Gastrointestinal Pharmacology', 4, '["Aminosalicylates, corticosteroids, immunomodulators, biologics"]'),
  ('pharmacology', 'respiratory-pharmacology-bronchodilators', 'Bronchodilators', 6, 'Respiratory Pharmacology', 1, '["Beta-2 agonists","Methylxanthines","Anticholinergics"]'),
  ('pharmacology', 'respiratory-pharmacology-anti-inflammatory-drugs-for-asthma', 'Anti-inflammatory Drugs for Asthma', 6, 'Respiratory Pharmacology', 2, '["Corticosteroids","Leukotriene modifiers","Mast cell stabilisers"]'),
  ('pharmacology', 'respiratory-pharmacology-antitussives-expectorants-and-mucolytics', 'Antitussives, Expectorants and Mucolytics', 6, 'Respiratory Pharmacology', 3, '["Classification and mechanisms"]'),
  ('pharmacology', 'respiratory-pharmacology-drugs-for-copd', 'Drugs for COPD', 6, 'Respiratory Pharmacology', 4, '["Treatment principles"]'),
  ('pharmacology', 'haemopoietic-pharmacology-haematinics', 'Haematinics', 7, 'Haemopoietic Pharmacology', 1, '["Iron preparations","Folic acid","Vitamin B12"]'),
  ('pharmacology', 'haemopoietic-pharmacology-erythropoietin-and-colony-stimulating-factors', 'Erythropoietin and Colony Stimulating Factors', 7, 'Haemopoietic Pharmacology', 2, '["Mechanism and clinical use"]'),
  ('pharmacology', 'haemopoietic-pharmacology-anticoagulants', 'Anticoagulants', 7, 'Haemopoietic Pharmacology', 3, '["Heparin (unfractionated and low molecular weight)","Warfarin","Direct oral anticoagulants (DOACs)"]'),
  ('pharmacology', 'haemopoietic-pharmacology-antiplatelet-drugs', 'Antiplatelet Drugs', 7, 'Haemopoietic Pharmacology', 4, '["Mechanism and clinical use"]'),
  ('pharmacology', 'haemopoietic-pharmacology-fibrinolytics-thrombolytics', 'Fibrinolytics/Thrombolytics', 7, 'Haemopoietic Pharmacology', 5, '["Mechanism and clinical use"]'),
  ('pharmacology', 'haemopoietic-pharmacology-drugs-for-bleeding-disorders', 'Drugs for Bleeding Disorders', 7, 'Haemopoietic Pharmacology', 6, '["Vitamin K","Antifibrinolytics"]'),
  ('pharmacology', 'endocrine-pharmacology-hypothalamic-pituitary-hormones-and-analogues', 'Hypothalamic-Pituitary Hormones and Analogues', 8, 'Endocrine Pharmacology', 1, '["Growth hormone, gonadotropins, ADH analogues"]'),
  ('pharmacology', 'endocrine-pharmacology-thyroid-and-antithyroid-drugs', 'Thyroid and Antithyroid Drugs', 8, 'Endocrine Pharmacology', 2, '["Thyroid hormone replacement","Antithyroid drugs (thionamides, iodine, radioactive iodine)"]'),
  ('pharmacology', 'endocrine-pharmacology-insulin-and-oral-hypoglycaemic-agents', 'Insulin and Oral Hypoglycaemic Agents', 8, 'Endocrine Pharmacology', 3, '["Insulin types and regimens","Sulfonylureas, biguanides, other oral agents","Newer agents (GLP-1 agonists, SGLT2 inhibitors)"]'),
  ('pharmacology', 'endocrine-pharmacology-corticosteroids', 'Corticosteroids', 8, 'Endocrine Pharmacology', 4, '["Glucocorticoids and mineralocorticoids","Clinical uses and adverse effects"]'),
  ('pharmacology', 'endocrine-pharmacology-sex-hormones-and-contraceptives', 'Sex Hormones and Contraceptives', 8, 'Endocrine Pharmacology', 5, '["Estrogens, progestins, androgens","Hormonal contraceptives"]'),
  ('pharmacology', 'endocrine-pharmacology-drugs-affecting-bone-mineral-homeostasis', 'Drugs Affecting Bone Mineral Homeostasis', 8, 'Endocrine Pharmacology', 6, '["Calcium and vitamin D","Bisphosphonates and other bone agents"]'),
  ('pharmacology', 'immunopharmacology-immunosuppressant-drugs', 'Immunosuppressant Drugs', 9, 'Immunopharmacology', 1, '["Calcineurin inhibitors","Antiproliferative/cytotoxic agents","Corticosteroids"]'),
  ('pharmacology', 'immunopharmacology-immunostimulants', 'Immunostimulants', 9, 'Immunopharmacology', 2, '["Mechanism and clinical use"]'),
  ('pharmacology', 'immunopharmacology-antihistamines', 'Antihistamines', 9, 'Immunopharmacology', 3, '["H1-receptor antagonists (first- and second-generation)"]'),
  ('pharmacology', 'immunopharmacology-biologics-and-monoclonal-antibodies', 'Biologics and Monoclonal Antibodies', 9, 'Immunopharmacology', 4, '["Mechanism and clinical use in autoimmune disease"]'),
  ('pharmacology', 'central-nervous-system-pharmacology-general-and-local-anaesthetics', 'General and Local Anaesthetics', 10, 'Central Nervous System Pharmacology', 1, '["Mechanism of action","Stages of general anaesthesia","Local anaesthetic agents"]'),
  ('pharmacology', 'central-nervous-system-pharmacology-sedative-hypnotics-and-anxiolytics', 'Sedative-Hypnotics and Anxiolytics', 10, 'Central Nervous System Pharmacology', 2, '["Benzodiazepines","Barbiturates","Newer non-benzodiazepine agents"]'),
  ('pharmacology', 'central-nervous-system-pharmacology-antiepileptic-drugs', 'Antiepileptic Drugs', 10, 'Central Nervous System Pharmacology', 3, '["Classification by mechanism","Choice of drug by seizure type"]'),
  ('pharmacology', 'central-nervous-system-pharmacology-antipsychotic-drugs', 'Antipsychotic Drugs', 10, 'Central Nervous System Pharmacology', 4, '["Typical and atypical antipsychotics"]'),
  ('pharmacology', 'central-nervous-system-pharmacology-antidepressants-and-mood-stabilisers', 'Antidepressants and Mood Stabilisers', 10, 'Central Nervous System Pharmacology', 5, '["SSRIs, TCAs, MAOIs, others","Lithium and mood stabilisers"]'),
  ('pharmacology', 'central-nervous-system-pharmacology-opioid-analgesics', 'Opioid Analgesics', 10, 'Central Nervous System Pharmacology', 6, '["Mechanism, agonists, partial agonists, antagonists"]'),
  ('pharmacology', 'central-nervous-system-pharmacology-non-opioid-analgesics-nsaids', 'Non-opioid Analgesics/NSAIDs', 10, 'Central Nervous System Pharmacology', 7, '["Mechanism of action","Adverse effects"]'),
  ('pharmacology', 'central-nervous-system-pharmacology-drugs-for-parkinsons-disease', 'Drugs for Parkinson''s Disease', 10, 'Central Nervous System Pharmacology', 8, '["Dopaminergic agents","Other classes"]'),
  ('pharmacology', 'central-nervous-system-pharmacology-drugs-for-alzheimers-disease-dementia', 'Drugs for Alzheimer''s Disease/Dementia', 10, 'Central Nervous System Pharmacology', 9, '["Cholinesterase inhibitors","NMDA receptor antagonists"]'),
  ('pharmacology', 'central-nervous-system-pharmacology-cns-stimulants', 'CNS Stimulants', 10, 'Central Nervous System Pharmacology', 10, '["Classification and uses"]'),
  ('pharmacology', 'toxicology-general-principles-of-toxicology', 'General Principles of Toxicology', 11, 'Toxicology', 1, '["Mechanisms of toxicity","Dose-response and toxicokinetics"]'),
  ('pharmacology', 'toxicology-management-of-poisoning', 'Management of Poisoning', 11, 'Toxicology', 2, '["General approach to the poisoned patient","Decontamination methods","Specific antidotes"]'),
  ('pharmacology', 'toxicology-specific-poisonings', 'Specific Poisonings', 11, 'Toxicology', 3, '["Heavy metals","Organophosphates","Other common poisons"]'),
  ('pharmacology', 'toxicology-drug-and-alcohol-abuse', 'Drug and Alcohol Abuse', 11, 'Toxicology', 4, '["Dependence and withdrawal syndromes"]'),
  ('pharmacology', 'system-4-chemotherapy-antibacterial-agents', 'Antibacterial Agents', 12, 'System 4: Chemotherapy', 1, '["Beta-lactams (penicillins, cephalosporins, carbapenems)","Aminoglycosides","Macrolides","Tetracyclines","Fluoroquinolones","Sulfonamides and trimethoprim","Other classes"]'),
  ('pharmacology', 'system-4-chemotherapy-antifungal-agents', 'Antifungal Agents', 12, 'System 4: Chemotherapy', 2, '["Classification and mechanisms"]'),
  ('pharmacology', 'system-4-chemotherapy-antiviral-agents', 'Antiviral Agents', 12, 'System 4: Chemotherapy', 3, '["Antiretrovirals","Other antivirals"]'),
  ('pharmacology', 'system-4-chemotherapy-antiprotozoal-agents', 'Antiprotozoal Agents', 12, 'System 4: Chemotherapy', 4, '["Antimalarials","Agents for other protozoal infections"]'),
  ('pharmacology', 'system-4-chemotherapy-anthelmintics', 'Anthelmintics', 12, 'System 4: Chemotherapy', 5, '["Classification and mechanisms"]'),
  ('pharmacology', 'system-4-chemotherapy-anticancer-antineoplastic-drugs', 'Anticancer/Antineoplastic Drugs', 12, 'System 4: Chemotherapy', 6, '["Cell-cycle specific and non-specific agents","Principles of combination chemotherapy"]'),
  ('pharmacology', 'system-4-chemotherapy-principles-of-chemotherapy-and-antimicrobial-resistance', 'Principles of Chemotherapy and Antimicrobial Resistance', 12, 'System 4: Chemotherapy', 7, '["Selective toxicity","Mechanisms of resistance"]'),
  ('anatomical-pathology', 'general-pathology-introduction-to-pathology', 'Introduction to Pathology', 1, 'General Pathology', 1, '[]'),
  ('anatomical-pathology', 'general-pathology-cellular-response-to-injury-part-1', 'Cellular Response to Injury (Part 1)', 1, 'General Pathology', 2, '["Definition","Types of cellular response","Causes of cell injury","Cellular adaptation","Reversible cell injury","Irreversible cell injury","Mechanism of injury"]'),
  ('anatomical-pathology', 'general-pathology-cellular-response-to-injury-part-2', 'Cellular Response to Injury (Part 2)', 1, 'General Pathology', 3, '["Cell death and types","Intracellular accumulations","Pathological calcifications","Cellular aging"]'),
  ('anatomical-pathology', 'general-pathology-inflammation-part-1', 'Inflammation (Part 1)', 1, 'General Pathology', 4, '["Definition","Classification","Events of inflammation","Mediators of inflammation","Outcome of acute inflammation"]'),
  ('anatomical-pathology', 'general-pathology-inflammation-part-2', 'Inflammation (Part 2)', 1, 'General Pathology', 5, '["Morphologic pattern of acute inflammation","Chronic inflammation","Systemic effect of inflammation","Consequences of defective or excessive inflammation"]'),
  ('anatomical-pathology', 'general-pathology-wound-healing', 'Wound Healing', 1, 'General Pathology', 6, '["Definition","Classification","Process of wound healing","Factors influencing wound healing","Abnormalities of wound healing"]'),
  ('anatomical-pathology', 'general-pathology-haemodynamic-disorders-part-1', 'Haemodynamic Disorders (Part 1)', 1, 'General Pathology', 7, '["Introduction","Hyperaemia and congestion","Thrombosis","Embolism","Oedema"]'),
  ('anatomical-pathology', 'general-pathology-haemodynamic-disorders-part-2', 'Haemodynamic Disorders (Part 2)', 1, 'General Pathology', 8, '["Infarction","Shock"]'),
  ('anatomical-pathology', 'general-pathology-genetic-disorders-part-1', 'Genetic Disorders (Part 1)', 1, 'General Pathology', 9, '["Introduction","Terminologies","Chromosomal disorders"]'),
  ('anatomical-pathology', 'general-pathology-genetic-disorders-part-2', 'Genetic Disorders (Part 2)', 1, 'General Pathology', 10, '["Single gene disorders","Classification (classical and non-classical disorders)","Classical disorders (Mendelian): Autosomal Dominant, Autosomal Recessive, X-linked Recessive, X-linked Dominant","Complex mutagenic disorders"]'),
  ('anatomical-pathology', 'general-pathology-neoplasm-part-1', 'Neoplasm (Part 1)', 1, 'General Pathology', 11, '["Definition","Epidemiology","Classification","Nomenclature","Difference between benign and malignant neoplasms","Molecular basis of cancer"]'),
  ('anatomical-pathology', 'general-pathology-neoplasm-part-2', 'Neoplasm (Part 2)', 1, 'General Pathology', 12, '["Carcinogenesis (chemical, radiation and microbial)","Spread of cancer","Clinical manifestation","Grading and staging","Laboratory diagnosis of cancer"]'),
  ('anatomical-pathology', 'general-pathology-disease-of-the-immune-system-part-1', 'Disease of the Immune System (Part 1)', 1, 'General Pathology', 13, '["Introduction","Classification of normal immunity (innate and adaptive)","Components of adaptive immunity","Immune disorder types","Hypersensitivity reactions","Autoimmunity disorders"]'),
  ('anatomical-pathology', 'general-pathology-disease-of-the-immune-system-part-2', 'Disease of the Immune System (Part 2)', 1, 'General Pathology', 14, '["Immune deficiency disease (primary and secondary)","Amyloidosis","Transplant rejection"]'),
  ('anatomical-pathology', 'general-pathology-disease-of-infancy-and-childhood', 'Disease of Infancy and Childhood', 1, 'General Pathology', 15, '["Classification","Specific types","Congenital anomalies","Prematurity disorders","Cystic fibrosis","Tumour and tumour-like lesions"]'),
  ('anatomical-pathology', 'general-pathology-disease-of-environment-nutrition', 'Disease of Environment / Nutrition', 1, 'General Pathology', 16, '["Definition of environmental disease","Classification of environmental factors (personal and external)","Effects of tobacco/smoking","Effects of alcohol","Nutritional disease","Malnutrition (kwashiorkor and marasmus)","Obesity"]'),
  ('anatomical-pathology', 'general-pathology-infectious-disease', 'Infectious Disease', 1, 'General Pathology', 17, '["Definition of infection","Route of entry of microbes","Spread in the body","Release from the body","Host-pathogen interaction","Host damage by microbes","Spectrum of inflammatory response to infection","Specific diseases: tuberculosis, malaria, syphilis"]'),
  ('anatomical-pathology', 'general-pathology-forensic-pathology', 'Forensic Pathology', 1, 'General Pathology', 18, '["Definition","Types (coroner and hospital)","Indications","Uses of autopsy","Examination (internal and external)","Death certification"]'),
  ('anatomical-pathology', 'cardiovascular-pathology-congenital-heart-diseases', 'Congenital Heart Diseases', 2, 'Cardiovascular Pathology', 1, '[]'),
  ('anatomical-pathology', 'cardiovascular-pathology-heart-failure', 'Heart Failure', 2, 'Cardiovascular Pathology', 2, '[]'),
  ('anatomical-pathology', 'cardiovascular-pathology-blood-vessel-disorders', 'Blood Vessel Disorders', 2, 'Cardiovascular Pathology', 3, '["Brief history of blood vessels","Arteriosclerosis","Atherosclerosis","Aneurysms"]'),
  ('anatomical-pathology', 'cardiovascular-pathology-myocardial-diseases', 'Myocardial Diseases', 2, 'Cardiovascular Pathology', 4, '["Emphasis on ischaemic heart disease and cardiomyopathies"]'),
  ('anatomical-pathology', 'cardiovascular-pathology-valvular-heart-disease', 'Valvular Heart Disease', 2, 'Cardiovascular Pathology', 5, '["Emphasis on rheumatic and infective endocarditis"]'),
  ('anatomical-pathology', 'cardiovascular-pathology-pericardial-diseases', 'Pericardial Diseases', 2, 'Cardiovascular Pathology', 6, '["Emphasis on pericarditis"]'),
  ('anatomical-pathology', 'central-nervous-system-pathology-cns-infections', 'CNS Infections', 3, 'Central Nervous System Pathology', 1, '["Meningitis","Encephalitis","Prion diseases (definition, types and clinical features)"]'),
  ('anatomical-pathology', 'central-nervous-system-pathology-intracranial-haemorrhages', 'Intracranial Haemorrhages', 3, 'Central Nervous System Pathology', 2, '[]'),
  ('anatomical-pathology', 'central-nervous-system-pathology-herniations', 'Herniations', 3, 'Central Nervous System Pathology', 3, '[]'),
  ('anatomical-pathology', 'central-nervous-system-pathology-hydrocephalus', 'Hydrocephalus', 3, 'Central Nervous System Pathology', 4, '[]'),
  ('anatomical-pathology', 'central-nervous-system-pathology-space-occupying-lesions', 'Space-Occupying Lesions', 3, 'Central Nervous System Pathology', 5, '["Emphasis on classification"]'),
  ('anatomical-pathology', 'central-nervous-system-pathology-cns-tumours', 'CNS Tumours', 3, 'Central Nervous System Pathology', 6, '["Emphasis on classification, clinical features and complications"]'),
  ('anatomical-pathology', 'central-nervous-system-pathology-cerebrovascular-disease-stroke', 'Cerebrovascular Disease (Stroke)', 3, 'Central Nervous System Pathology', 7, '[]'),
  ('anatomical-pathology', 'central-nervous-system-pathology-neurodegenerative-diseases', 'Neurodegenerative Diseases', 3, 'Central Nervous System Pathology', 8, '["Definition and classification"]'),
  ('anatomical-pathology', 'autopsy-pathology-autopsy-pathology', 'Autopsy Pathology', 4, 'Autopsy Pathology', 1, '[]'),
  ('anatomical-pathology', 'respiratory-pathology-obstructive-vs-restrictive-lung-disease', 'Obstructive vs Restrictive Lung Disease', 5, 'Respiratory Pathology', 1, '["Difference between obstructive and restrictive lung diseases"]'),
  ('anatomical-pathology', 'respiratory-pathology-obstructive-lung-diseases', 'Obstructive Lung Diseases', 5, 'Respiratory Pathology', 2, '["Emphasis on COPD and bronchiectasis"]'),
  ('anatomical-pathology', 'respiratory-pathology-respiratory-neoplasms', 'Respiratory Neoplasms', 5, 'Respiratory Pathology', 3, '["Lung cancer","Mesothelioma"]'),
  ('anatomical-pathology', 'respiratory-pathology-pneumonia', 'Pneumonia', 5, 'Respiratory Pathology', 4, '[]'),
  ('anatomical-pathology', 'respiratory-pathology-pulmonary-embolism', 'Pulmonary Embolism', 5, 'Respiratory Pathology', 5, '[]'),
  ('anatomical-pathology', 'respiratory-pathology-asthma', 'Asthma', 5, 'Respiratory Pathology', 6, '[]'),
  ('anatomical-pathology', 'respiratory-pathology-tuberculosis', 'Tuberculosis', 5, 'Respiratory Pathology', 7, '[]'),
  ('anatomical-pathology', 'respiratory-pathology-restrictive-lung-disease', 'Restrictive Lung Disease', 5, 'Respiratory Pathology', 8, '["Classification","Short note on pneumoconiosis"]'),
  ('anatomical-pathology', 'renal-pathology-overview-of-renal-diseases', 'Overview of Renal Diseases', 6, 'Renal Pathology', 1, '["Emphasis on classification"]'),
  ('anatomical-pathology', 'renal-pathology-glomerular-diseases', 'Glomerular Diseases', 6, 'Renal Pathology', 2, '["Classification, syndrome manifestation, terminologies (e.g. hypercellularity, sclerosis)"]'),
  ('anatomical-pathology', 'renal-pathology-tubulo-interstitial-diseases', 'Tubulo-interstitial Diseases', 6, 'Renal Pathology', 3, '[]'),
  ('anatomical-pathology', 'renal-pathology-pyelonephritis', 'Pyelonephritis', 6, 'Renal Pathology', 4, '[]'),
  ('anatomical-pathology', 'renal-pathology-acute-tubular-injury', 'Acute Tubular Injury', 6, 'Renal Pathology', 5, '[]'),
  ('anatomical-pathology', 'renal-pathology-cystic-diseases-of-the-kidney', 'Cystic Diseases of the Kidney', 6, 'Renal Pathology', 6, '["Emphasis on classification and polycystic kidney disease"]'),
  ('anatomical-pathology', 'renal-pathology-congenital-anomalies', 'Congenital Anomalies', 6, 'Renal Pathology', 7, '[]'),
  ('anatomical-pathology', 'renal-pathology-renal-stones', 'Renal Stones', 6, 'Renal Pathology', 8, '[]'),
  ('anatomical-pathology', 'renal-pathology-renal-cancers', 'Renal Cancers', 6, 'Renal Pathology', 9, '[]'),
  ('anatomical-pathology', 'gastrointestinal-pathology-oesophageal-disorders', 'Oesophageal Disorders', 7, 'Gastrointestinal Pathology', 1, '["Congenital disorders","Obstructive lesions","Inflammatory conditions","Barrett''s oesophagus","Cancers"]'),
  ('anatomical-pathology', 'gastrointestinal-pathology-stomach-disorders', 'Stomach Disorders', 7, 'Gastrointestinal Pathology', 2, '["Gastritis (acute/chronic/peptic ulcer disease)","Gastric cancers"]'),
  ('anatomical-pathology', 'gastrointestinal-pathology-intestinal-disorders', 'Intestinal Disorders', 7, 'Gastrointestinal Pathology', 3, '["Intussusception","Inflammatory bowel disease","Carcinoid tumour (short note; relationship to neuroendocrine tumour)"]'),
  ('anatomical-pathology', 'gastrointestinal-pathology-colonic-disorders', 'Colonic Disorders', 7, 'Gastrointestinal Pathology', 4, '["Colonic polyps","Colonic cancers","Hirschsprung''s disease"]'),
  ('anatomical-pathology', 'gastrointestinal-pathology-liver-disease', 'Liver Disease', 7, 'Gastrointestinal Pathology', 5, '["Liver cirrhosis","Liver cancer"]'),
  ('anatomical-pathology', 'hepatobiliary-pathology-gallbladder-disease', 'Gallbladder Disease', 8, 'Hepatobiliary Pathology', 1, '["Gall stones","Cholecystitis"]'),
  ('anatomical-pathology', 'female-genital-tract-pathology-ovarian-tumours', 'Ovarian Tumours', 9, 'Female Genital Tract Pathology', 1, '["Emphasis on classification, clinical features and complications","Teratoma and salient features of yolk sac tumour"]'),
  ('anatomical-pathology', 'female-genital-tract-pathology-uterine-disease', 'Uterine Disease', 9, 'Female Genital Tract Pathology', 2, '["Leiomyoma","Endometrial cancer"]'),
  ('anatomical-pathology', 'female-genital-tract-pathology-cervical-cancers', 'Cervical Cancers', 9, 'Female Genital Tract Pathology', 3, '[]'),
  ('anatomical-pathology', 'female-genital-tract-pathology-gestational-trophoblastic-disease-gtd', 'Gestational Trophoblastic Disease (GTD)', 9, 'Female Genital Tract Pathology', 4, '["Emphasis on molar pregnancy and choriocarcinoma"]'),
  ('anatomical-pathology', 'endocrine-pathology-thyroid-diseases', 'Thyroid Diseases', 10, 'Endocrine Pathology', 1, '["Emphasis on goitre, autoimmune disorders, inflammatory conditions and neoplasms"]'),
  ('anatomical-pathology', 'endocrine-pathology-adrenal-medullary-tumours', 'Adrenal/Medullary Tumours', 10, 'Endocrine Pathology', 2, '[]'),
  ('anatomical-pathology', 'endocrine-pathology-men-syndromes', 'MEN Syndromes', 10, 'Endocrine Pathology', 3, '[]'),
  ('anatomical-pathology', 'endocrine-pathology-diabetes-mellitus', 'Diabetes Mellitus', 10, 'Endocrine Pathology', 4, '[]'),
  ('anatomical-pathology', 'breast-pathology-classification-of-breast-diseases', 'Classification of Breast Diseases', 11, 'Breast Pathology', 1, '[]'),
  ('anatomical-pathology', 'breast-pathology-breast-cancers', 'Breast Cancers', 11, 'Breast Pathology', 2, '[]'),
  ('anatomical-pathology', 'male-genital-tract-and-bladder-pathology-prostate-disorders', 'Prostate Disorders', 12, 'Male Genital Tract and Bladder Pathology', 1, '["Benign prostatic hyperplasia and cancers"]'),
  ('anatomical-pathology', 'male-genital-tract-and-bladder-pathology-bladder-cancers', 'Bladder Cancers', 12, 'Male Genital Tract and Bladder Pathology', 2, '[]'),
  ('anatomical-pathology', 'bone-and-soft-tissue-disorders-osteomyelitis', 'Osteomyelitis', 13, 'Bone and Soft Tissue Disorders', 1, '[]'),
  ('anatomical-pathology', 'bone-and-soft-tissue-disorders-classification-of-bone-tumours', 'Classification of Bone Tumours', 13, 'Bone and Soft Tissue Disorders', 2, '[]'),
  ('anatomical-pathology', 'bone-and-soft-tissue-disorders-arthritis', 'Arthritis', 13, 'Bone and Soft Tissue Disorders', 3, '["Classification and basic features of osteoarthritis and rheumatoid arthritis"]'),
  ('anatomical-pathology', 'bone-and-soft-tissue-disorders-classification-of-soft-tissue-tumours', 'Classification of Soft Tissue Tumours', 13, 'Bone and Soft Tissue Disorders', 4, '[]'),
  ('anatomical-pathology', 'skin-pathology-terminologies', 'Terminologies', 14, 'Skin Pathology', 1, '["Primary and secondary skin lesions (macules, papules, bullae, etc.)"]'),
  ('anatomical-pathology', 'skin-pathology-inflammatory-dermatoses', 'Inflammatory Dermatoses', 14, 'Skin Pathology', 2, '["Classification: spongiotic, lichenoid, psoriasiform and blistering disorders (with examples)"]'),
  ('anatomical-pathology', 'skin-pathology-neoplasms', 'Neoplasms', 14, 'Skin Pathology', 3, '[]'),
  ('chemical-pathology', 'introduction-and-laboratory-basics-introduction-to-chemical-pathology-and-the-role-of-the', 'Introduction to chemical pathology and the role of the chemical pathologist', 1, 'Introduction and Laboratory Basics', 1, '[]'),
  ('chemical-pathology', 'introduction-and-laboratory-basics-types-of-biological-specimen-and-biological-variation', 'Types of biological specimen and biological variation', 1, 'Introduction and Laboratory Basics', 2, '[]'),
  ('chemical-pathology', 'introduction-and-laboratory-basics-point-of-care-testing-principles-and-application', 'Point of care testing: principles and application', 1, 'Introduction and Laboratory Basics', 3, '[]'),
  ('chemical-pathology', 'introduction-and-laboratory-basics-factors-affecting-laboratory-results-pre-analytical-and', 'Factors affecting laboratory results (pre-analytical and post-analytical sources of error)', 1, 'Introduction and Laboratory Basics', 4, '[]'),
  ('chemical-pathology', 'introduction-and-laboratory-basics-role-of-the-physician-in-reducing-laboratory-errors', 'Role of the physician in reducing laboratory errors', 1, 'Introduction and Laboratory Basics', 5, '[]'),
  ('chemical-pathology', 'introduction-and-laboratory-basics-laboratory-safety', 'Laboratory safety', 1, 'Introduction and Laboratory Basics', 6, '[]'),
  ('chemical-pathology', 'introduction-and-laboratory-basics-automation-in-the-laboratory', 'Automation in the laboratory', 1, 'Introduction and Laboratory Basics', 7, '[]'),
  ('chemical-pathology', 'introduction-and-laboratory-basics-chemical-pathology-and-the-application-of-artificial-in', 'Chemical pathology and the application of artificial intelligence (AI)', 1, 'Introduction and Laboratory Basics', 8, '[]'),
  ('chemical-pathology', 'immunology-basic-concepts-basic-concepts-of-immunology-immunoglobulin-structures-propertie', 'Basic concepts of immunology: immunoglobulin structures, properties and functions', 2, 'Immunology (Basic Concepts)', 1, '[]'),
  ('chemical-pathology', 'immunology-basic-concepts-cytokine-storm', 'Cytokine storm', 2, 'Immunology (Basic Concepts)', 2, '[]'),
  ('chemical-pathology', 'renal-chemistry-renal-function-tests', 'Renal function tests', 3, 'Renal Chemistry', 1, '[]'),
  ('chemical-pathology', 'renal-chemistry-renal-tubular-acidosis', 'Renal tubular acidosis', 3, 'Renal Chemistry', 2, '[]'),
  ('chemical-pathology', 'renal-chemistry-types-of-urine-samples', 'Types of urine samples', 3, 'Renal Chemistry', 3, '[]'),
  ('chemical-pathology', 'renal-chemistry-urinalysis', 'Urinalysis', 3, 'Renal Chemistry', 4, '[]'),
  ('chemical-pathology', 'renal-chemistry-water-and-sodium-balance-and-disorders', 'Water and sodium balance and disorders', 3, 'Renal Chemistry', 5, '[]'),
  ('chemical-pathology', 'carbohydrate-metabolism-glucose-homeostasis', 'Glucose homeostasis', 4, 'Carbohydrate Metabolism', 1, '[]'),
  ('chemical-pathology', 'carbohydrate-metabolism-diabetes-mellitus-and-its-complications', 'Diabetes mellitus and its complications', 4, 'Carbohydrate Metabolism', 2, '[]'),
  ('chemical-pathology', 'carbohydrate-metabolism-hypoglycaemia', 'Hypoglycaemia', 4, 'Carbohydrate Metabolism', 3, '[]'),
  ('chemical-pathology', 'carbohydrate-metabolism-oral-glucose-tolerance-test-ogtt', 'Oral glucose tolerance test (OGTT)', 4, 'Carbohydrate Metabolism', 4, '[]'),
  ('chemical-pathology', 'carbohydrate-metabolism-gestational-diabetes-mellitus', 'Gestational diabetes mellitus', 4, 'Carbohydrate Metabolism', 5, '[]'),
  ('chemical-pathology', 'carbohydrate-metabolism-inborn-errors-of-carbohydrate-metabolism', 'Inborn errors of carbohydrate metabolism', 4, 'Carbohydrate Metabolism', 6, '[]'),
  ('chemical-pathology', 'nutrition-and-substance-related-biochemistry-biochemistry-of-alcohol-abuse', 'Biochemistry of alcohol abuse', 5, 'Nutrition and Substance-Related Biochemistry', 1, '[]'),
  ('chemical-pathology', 'nutrition-and-substance-related-biochemistry-water-soluble-vitamins', 'Water-soluble vitamins', 5, 'Nutrition and Substance-Related Biochemistry', 2, '[]'),
  ('chemical-pathology', 'nutrition-and-substance-related-biochemistry-obesity', 'Obesity', 5, 'Nutrition and Substance-Related Biochemistry', 3, '[]'),
  ('chemical-pathology', 'nutrition-and-substance-related-biochemistry-metabolic-syndrome', 'Metabolic syndrome', 5, 'Nutrition and Substance-Related Biochemistry', 4, '[]'),
  ('chemical-pathology', 'nutrition-and-substance-related-biochemistry-trace-elements-and-metals', 'Trace elements and metals', 5, 'Nutrition and Substance-Related Biochemistry', 5, '[]'),
  ('chemical-pathology', 'nutrition-and-substance-related-biochemistry-nutrition-nutritional-support', 'Nutrition/nutritional support', 5, 'Nutrition and Substance-Related Biochemistry', 6, '[]'),
  ('chemical-pathology', 'nutrition-and-substance-related-biochemistry-malabsorption-syndrome', 'Malabsorption syndrome', 5, 'Nutrition and Substance-Related Biochemistry', 7, '[]'),
  ('chemical-pathology', 'nutrition-and-substance-related-biochemistry-investigations-of-malabsorption-syndrome', 'Investigations of malabsorption syndrome', 5, 'Nutrition and Substance-Related Biochemistry', 8, '[]'),
  ('chemical-pathology', 'electrolyte-acid-base-and-mineral-homeostasis-potassium-homeostasis-and-disorders', 'Potassium homeostasis and disorders', 6, 'Electrolyte, Acid-Base and Mineral Homeostasis', 1, '[]'),
  ('chemical-pathology', 'electrolyte-acid-base-and-mineral-homeostasis-acid-base-balance', 'Acid-base balance', 6, 'Electrolyte, Acid-Base and Mineral Homeostasis', 2, '[]'),
  ('chemical-pathology', 'electrolyte-acid-base-and-mineral-homeostasis-disorders-of-acid-base-balance-interpretatio', 'Disorders of acid-base balance / interpretation', 6, 'Electrolyte, Acid-Base and Mineral Homeostasis', 3, '[]'),
  ('chemical-pathology', 'electrolyte-acid-base-and-mineral-homeostasis-calcium-phosphate-and-magnesium-homeostasis', 'Calcium, phosphate and magnesium homeostasis and disorders', 6, 'Electrolyte, Acid-Base and Mineral Homeostasis', 4, '[]'),
  ('chemical-pathology', 'electrolyte-acid-base-and-mineral-homeostasis-metabolic-bone-disease', 'Metabolic bone disease', 6, 'Electrolyte, Acid-Base and Mineral Homeostasis', 5, '[]'),
  ('chemical-pathology', 'endocrinology-introduction-to-endocrinology-and-mechanism-of-action-of-hormones', 'Introduction to endocrinology and mechanism of action of hormones', 7, 'Endocrinology', 1, '[]'),
  ('chemical-pathology', 'endocrinology-hypothalamus-pituitary-gland', 'Hypothalamus-pituitary gland', 7, 'Endocrinology', 2, '[]'),
  ('chemical-pathology', 'endocrinology-thyroid-axis-and-disorders', 'Thyroid axis and disorders', 7, 'Endocrinology', 3, '[]'),
  ('chemical-pathology', 'endocrinology-adrenal-axis-and-disorders', 'Adrenal axis and disorders', 7, 'Endocrinology', 4, '[]'),
  ('chemical-pathology', 'endocrinology-gonadal-axis-and-disorders-infertility', 'Gonadal axis and disorders / infertility', 7, 'Endocrinology', 5, '[]'),
  ('chemical-pathology', 'proteins-enzymes-and-tumour-markers-plasma-enzymes-in-diagnosis', 'Plasma enzymes in diagnosis', 8, 'Proteins, Enzymes and Tumour Markers', 1, '[]'),
  ('chemical-pathology', 'proteins-enzymes-and-tumour-markers-tumor-markers-paraneoplastic-syndrome', 'Tumor markers / paraneoplastic syndrome', 8, 'Proteins, Enzymes and Tumour Markers', 2, '[]'),
  ('chemical-pathology', 'proteins-enzymes-and-tumour-markers-metabolic-effects-of-tumors-carcinoid-syndrome-men-etc', 'Metabolic effects of tumors (carcinoid syndrome, MEN, etc.)', 8, 'Proteins, Enzymes and Tumour Markers', 3, '[]'),
  ('chemical-pathology', 'proteins-enzymes-and-tumour-markers-plasma-protein-and-its-disorders', 'Plasma protein and its disorders', 8, 'Proteins, Enzymes and Tumour Markers', 4, '[]'),
  ('chemical-pathology', 'proteins-enzymes-and-tumour-markers-plasma-lipids-and-disorders', 'Plasma lipids and disorders', 8, 'Proteins, Enzymes and Tumour Markers', 5, '[]'),
  ('chemical-pathology', 'organ-specific-chemical-pathology-liver-function-test', 'Liver function test', 9, 'Organ-Specific Chemical Pathology', 1, '[]'),
  ('chemical-pathology', 'organ-specific-chemical-pathology-cardiac-markers', 'Cardiac markers', 9, 'Organ-Specific Chemical Pathology', 2, '[]'),
  ('chemical-pathology', 'organ-specific-chemical-pathology-chemical-pathology-of-hypertension', 'Chemical pathology of hypertension', 9, 'Organ-Specific Chemical Pathology', 3, '[]'),
  ('chemical-pathology', 'organ-specific-chemical-pathology-csf-in-health-and-disease', 'CSF in health and disease', 9, 'Organ-Specific Chemical Pathology', 4, '[]'),
  ('chemical-pathology', 'inborn-errors-and-special-topics-inborn-errors-of-amino-acid-metabolism', 'Inborn errors of amino acid metabolism', 10, 'Inborn Errors and Special Topics', 1, '[]'),
  ('chemical-pathology', 'inborn-errors-and-special-topics-haem-metabolism-and-disorders-porphyria', 'Haem metabolism and disorders (porphyria)', 10, 'Inborn Errors and Special Topics', 2, '[]'),
  ('chemical-pathology', 'inborn-errors-and-special-topics-purine-and-urate-metabolism-and-disorders', 'Purine and urate metabolism and disorders', 10, 'Inborn Errors and Special Topics', 3, '[]'),
  ('chemical-pathology', 'special-populations-and-clinical-contexts-clinical-pathology-of-the-newborn', 'Clinical pathology of the newborn', 11, 'Special Populations and Clinical Contexts', 1, '[]'),
  ('chemical-pathology', 'special-populations-and-clinical-contexts-chemical-pathology-of-pregnancy', 'Chemical pathology of pregnancy', 11, 'Special Populations and Clinical Contexts', 2, '[]'),
  ('chemical-pathology', 'special-populations-and-clinical-contexts-geriatric-chemical-pathology', 'Geriatric chemical pathology', 11, 'Special Populations and Clinical Contexts', 3, '[]'),
  ('chemical-pathology', 'special-populations-and-clinical-contexts-endocrinopathology-of-hiv-aids', 'Endocrinopathology of HIV/AIDS', 11, 'Special Populations and Clinical Contexts', 4, '[]'),
  ('chemical-pathology', 'therapeutic-monitoring-and-toxicology-therapeutic-drug-monitoring', 'Therapeutic drug monitoring', 12, 'Therapeutic Monitoring and Toxicology', 1, '[]'),
  ('chemical-pathology', 'therapeutic-monitoring-and-toxicology-occupational-health-testing-monitoring-of-exposed-wo', 'Occupational health testing (monitoring of exposed workers)', 12, 'Therapeutic Monitoring and Toxicology', 2, '[]'),
  ('chemical-pathology', 'therapeutic-monitoring-and-toxicology-drug-of-abuse-testing', 'Drug of abuse testing', 12, 'Therapeutic Monitoring and Toxicology', 3, '[]'),
  ('microbiology', '1-introduction-to-medical-microbiology-introduction-to-medical-microbiology', 'Introduction to Medical Microbiology', 1, '1. Introduction to Medical Microbiology', 1, '["Definition","Infectious agents","Classification of microorganisms","Infection triad: Environment, Organisms, Host"]'),
  ('microbiology', '1-introduction-to-medical-microbiology-history-and-development-of-medical-microbiology', 'History and Development of Medical Microbiology', 1, '1. Introduction to Medical Microbiology', 2, '["Notable events","Scientists and contributions"]'),
  ('microbiology', '1-introduction-to-medical-microbiology-definition-of-terms', 'Definition of Terms', 1, '1. Introduction to Medical Microbiology', 3, '["Pathogens","Normal microbiota","Infection","Infestation","Pathogenicity","Virulence"]'),
  ('microbiology', '1-introduction-to-medical-microbiology-basic-microscopy', 'Basic Microscopy', 1, '1. Introduction to Medical Microbiology', 4, '["Types of microscopes","Parts of microscopes and functions","Resolution","Lens power"]'),
  ('microbiology', '1-introduction-to-medical-microbiology-relationship-of-medical-microbiology', 'Relationship of Medical Microbiology', 1, '1. Introduction to Medical Microbiology', 5, '["To clinical medicine","To public health"]'),
  ('microbiology', '2-basic-mycology-parasitology-and-virology-basic-mycology', 'Basic Mycology', 2, '2. Basic Mycology, Parasitology and Virology', 1, '["Definition of terms","Characteristics of fungi","Types of fungal disorders","Classification of mycoses"]'),
  ('microbiology', '2-basic-mycology-parasitology-and-virology-basic-parasitology', 'Basic Parasitology', 2, '2. Basic Mycology, Parasitology and Virology', 2, '["Definition of terms","Characteristics of parasites","Host-parasite relationships","Classification of parasites"]'),
  ('microbiology', '2-basic-mycology-parasitology-and-virology-basic-virology', 'Basic Virology', 2, '2. Basic Mycology, Parasitology and Virology', 3, '["Definition of terms","Characteristics of viruses","Viral replication","Viral morphology","Viral metabolism"]'),
  ('microbiology', '3-basic-bacteriology-morphology-and-classification-of-bacteria', 'Morphology and Classification of Bacteria', 3, '3. Basic Bacteriology', 1, '["Morphology of bacteria","Bacterial cell wall structure and significance","Classification by nutritional requirements, oxygen requirement, temperature requirement","Effect of pH"]'),
  ('microbiology', '3-basic-bacteriology-bacterial-metabolism', 'Bacterial Metabolism', 3, '3. Basic Bacteriology', 2, '["Oxidation pathway","Fermentation pathway","Bacterial multiplication","Bacterial growth (growth curve)","Applications in artificial culture"]'),
  ('microbiology', '3-basic-bacteriology-bacterial-genetics', 'Bacterial Genetics', 3, '3. Basic Bacteriology', 3, '["Concept of protein synthesis","Microbial mutations","Gene transfers","Plasmids, bacteriophage","Human genomic project and application","Biotechnology and applications"]'),
  ('microbiology', '4-laboratory-procedures-and-infection-control-laboratory-procedures-in-medical-microbiolog', 'Laboratory Procedures in Medical Microbiology', 4, '4. Laboratory Procedures and Infection Control', 1, '["Staining techniques: Gram, Ziehl-Neelsen, KOH, Giemsa, Field stain, Saline wet mount, Albert stain, Capsular stains","Culture media: classification, uses","Laboratory safety, analytic phases, specimen handling, request form data"]'),
  ('microbiology', '4-laboratory-procedures-and-infection-control-basic-principles-of-sterilization-and-disinf', 'Basic Principles of Sterilization and Disinfection', 4, '4. Laboratory Procedures and Infection Control', 2, '["Classification of sterilization methods","Definitions: Asepsis, Antisepsis, Sterilization","Classification of medical devices and sterilization method utilised"]'),
  ('microbiology', '4-laboratory-procedures-and-infection-control-infection-prevention-and-control', 'Infection Prevention and Control', 4, '4. Laboratory Procedures and Infection Control', 3, '["Basic principles","Standard precautions","Transmission-based precautions","Hand hygiene"]'),
  ('microbiology', '4-laboratory-procedures-and-infection-control-diagnostic-techniques', 'Diagnostic Techniques', 4, '4. Laboratory Procedures and Infection Control', 4, '["Molecular diagnostic techniques","Serologic diagnostic techniques"]'),
  ('microbiology', '5-microbial-pathogenicity-and-chemotherapy-microbial-pathogenicity', 'Microbial Pathogenicity', 5, '5. Microbial Pathogenicity and Chemotherapy', 1, '["Concept of normal flora","Infection and immunity","Concept of communicability","Pathogenesis of infectious diseases"]'),
  ('microbiology', '5-microbial-pathogenicity-and-chemotherapy-chemotherapy-of-infections', 'Chemotherapy of Infections', 5, '5. Microbial Pathogenicity and Chemotherapy', 2, '["Principles and practice","Classification of antimicrobials and mechanisms of action"]'),
  ('microbiology', '5-microbial-pathogenicity-and-chemotherapy-antimicrobial-resistance', 'Antimicrobial Resistance', 5, '5. Microbial Pathogenicity and Chemotherapy', 3, '["Origins","Ambler and Bush classifications","AmpC","ESBLs","Carbapenemases","MRSA, VRE","Basic concepts of antimicrobial stewardship"]'),
  ('microbiology', '5-microbial-pathogenicity-and-chemotherapy-anaerobes', 'Anaerobes', 5, '5. Microbial Pathogenicity and Chemotherapy', 4, '["Concept of anaerobiosis","Characteristics of anaerobes","Classification of anaerobes","Anaerobic infections: Clostridium spp, Bacteroides spp, Actinomyces spp"]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-staphylococcus-spp', 'Staphylococcus spp', 6, '6. Systematic Bacteriology (Specific Organisms)', 1, '["S. aureus, S. saprophyticus, S. epidermidis","Virulence factors","Clinical manifestations","Diagnosis","Treatment"]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-streptococcus-spp', 'Streptococcus spp', 6, '6. Systematic Bacteriology (Specific Organisms)', 2, '["Classification","S. pyogenes, S. agalactiae","S. pneumoniae, Enterococcus, Viridans streptococci"]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-mycobacteria', 'Mycobacteria', 6, '6. Systematic Bacteriology (Specific Organisms)', 3, '["Classification","M. tuberculosis, DR-TB","M. leprae — pathogenesis, clinical features, diagnosis, treatment"]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-enterobacterales', 'Enterobacterales', 6, '6. Systematic Bacteriology (Specific Organisms)', 4, '["General characteristics and classification","Escherichia coli: EIEC, EHEC, EAEC, EPEC — laboratory diagnosis","Klebsiella spp, Enterobacter","Salmonella spp, Shigella spp","Proteus spp, Citrobacter spp"]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-pseudomonas-spp-and-acinetobacter-spp', 'Pseudomonas spp and Acinetobacter spp', 6, '6. Systematic Bacteriology (Specific Organisms)', 5, '[]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-vibrio-spp-campylobacter-spp-helicobacter-spp', 'Vibrio spp, Campylobacter spp, Helicobacter spp', 6, '6. Systematic Bacteriology (Specific Organisms)', 6, '[]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-haemophilus-influenzae-and-haemophilus-ducrey', 'Haemophilus influenzae and Haemophilus ducreyi', 6, '6. Systematic Bacteriology (Specific Organisms)', 7, '[]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-yersinia-spp-and-bordetella-pertussis', 'Yersinia spp and Bordetella pertussis', 6, '6. Systematic Bacteriology (Specific Organisms)', 8, '[]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-neisseria-gonorrhoeae-and-neisseria-meningiti', 'Neisseria gonorrhoeae and Neisseria meningitidis', 6, '6. Systematic Bacteriology (Specific Organisms)', 9, '[]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-legionella-bartonella-bacterial-vaginosis-whi', 'Legionella, Bartonella, Bacterial Vaginosis, Whipple Disease', 6, '6. Systematic Bacteriology (Specific Organisms)', 10, '[]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-treponema-pallidum-and-borrelia-spp', 'Treponema pallidum and Borrelia spp', 6, '6. Systematic Bacteriology (Specific Organisms)', 11, '[]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-mycoplasma-spp-ureaplasma-urealyticum-rickett', 'Mycoplasma spp, Ureaplasma urealyticum, Rickettsia', 6, '6. Systematic Bacteriology (Specific Organisms)', 12, '[]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-chlamydia-lymphogranuloma-venereum-lgv-chlamy', 'Chlamydia, Lymphogranuloma Venereum (LGV), Chlamydophila pneumoniae', 6, '6. Systematic Bacteriology (Specific Organisms)', 13, '[]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-brucella-spp-francisella-spp-pasteurella-spp', 'Brucella spp, Francisella spp, Pasteurella spp', 6, '6. Systematic Bacteriology (Specific Organisms)', 14, '[]'),
  ('microbiology', '6-systematic-bacteriology-specific-organisms-burkholderia-spp-stenotrophomonas-spp-moraxel', 'Burkholderia spp, Stenotrophomonas spp, Moraxella spp', 6, '6. Systematic Bacteriology (Specific Organisms)', 15, '[]'),
  ('microbiology', '7-systematic-mycology-specific-fungal-infections-superficial-and-cutaneous-mycoses', 'Superficial and Cutaneous Mycoses', 7, '7. Systematic Mycology (Specific Fungal Infections)', 1, '["Dermatophytosis"]'),
  ('microbiology', '7-systematic-mycology-specific-fungal-infections-subcutaneous-and-systemic-mycoses', 'Subcutaneous and Systemic Mycoses', 7, '7. Systematic Mycology (Specific Fungal Infections)', 2, '[]'),
  ('microbiology', '7-systematic-mycology-specific-fungal-infections-opportunistic-mycoses', 'Opportunistic Mycoses', 7, '7. Systematic Mycology (Specific Fungal Infections)', 3, '["Candidiasis","Cryptococcosis","Aspergillosis","Pneumocystis jiroveci"]'),
  ('microbiology', '8-systematic-parasitology-protozoa-amoebae', 'Amoebae', 8, '8. Systematic Parasitology — Protozoa', 1, '["Pathogenic: E. histolytica","Non-pathogenic","Opportunistic: Naegleria fowleri, Acanthamoeba spp"]'),
  ('microbiology', '8-systematic-parasitology-protozoa-flagellates', 'Flagellates', 8, '8. Systematic Parasitology — Protozoa', 2, '["Intestinal: Giardia lamblia","Genital: Trichomonas vaginalis","Blood and tissue: Leishmania — classification, epidemiology, lifecycle, pathogenesis, clinical syndrome, diagnosis, treatment/prevention","Blood and tissue: Trypanosomes — classification, epidemiology, lifecycle, pathogenesis, clinical syndrome, diagnosis, treatment/prevention"]'),
  ('microbiology', '8-systematic-parasitology-protozoa-sporozoa', 'Sporozoa', 8, '8. Systematic Parasitology — Protozoa', 3, '["Toxoplasma gondii, Babesia, Isospora belli, Balantidium coli, Microsporidia","Malaria parasites: types, epidemiology, lifecycle, pathogenesis, clinical features, complications, diagnosis, treatment/prevention"]'),
  ('microbiology', '9-systematic-parasitology-helminths-cestodes', 'Cestodes', 9, '9. Systematic Parasitology — Helminths', 1, '["General characteristics and classification","Diphyllobothrium latum, Taenia spp","Hymenolepis nana, Echinococcus spp"]'),
  ('microbiology', '9-systematic-parasitology-helminths-trematodes', 'Trematodes', 9, '9. Systematic Parasitology — Helminths', 2, '["General characteristics and classification","Schistosomiasis","Fasciola spp, Paragonimus spp"]'),
  ('microbiology', '9-systematic-parasitology-helminths-nematodes', 'Nematodes', 9, '9. Systematic Parasitology — Helminths', 3, '["Intestinal: Enterobius vermicularis, Trichuris trichiura, Ascaris lumbricoides, Necator americanus, Ancylostoma duodenale","Intestinal and tissue: Strongyloides stercoralis, Trichinella spiralis","Tissue: Brugia malayi, Onchocerca volvulus, Loa loa, Wuchereria bancrofti"]'),
  ('microbiology', '9-systematic-parasitology-helminths-dracunculus-medinensis-and-larva-migrans', 'Dracunculus medinensis and Larva Migrans', 9, '9. Systematic Parasitology — Helminths', 4, '[]'),
  ('microbiology', '10-systematic-virology-pathogenesis-of-viral-diseases-and-adenovirus', 'Pathogenesis of Viral Diseases and Adenovirus', 10, '10. Systematic Virology', 1, '["Human adenovirus infections"]'),
  ('microbiology', '10-systematic-virology-herpesviruses', 'Herpesviruses', 10, '10. Systematic Virology', 2, '["Herpes simplex 1 & 2, Varicella-zoster","Cytomegalovirus, Epstein-Barr virus, HHV6, HHV7, HHV8"]'),
  ('microbiology', '10-systematic-virology-hepatitis-viruses', 'Hepatitis Viruses', 10, '10. Systematic Virology', 3, '["HAV, HBV, HCV","HDV, HEV"]'),
  ('microbiology', '10-systematic-virology-poxviruses', 'Poxviruses', 10, '10. Systematic Virology', 4, '["Smallpox, MPox, Molluscum contagiosum"]'),
  ('microbiology', '10-systematic-virology-picornaviruses-and-parvovirus', 'Picornaviruses and Parvovirus', 10, '10. Systematic Virology', 5, '["Poliovirus, Coxsackie virus","Parvovirus B-19"]'),
  ('microbiology', '10-systematic-virology-respiratory-viruses', 'Respiratory Viruses', 10, '10. Systematic Virology', 6, '["Influenza virus, Parainfluenza virus, Rhinovirus, Respiratory syncytial virus"]'),
  ('microbiology', '10-systematic-virology-paramyxoviruses-and-rabies', 'Paramyxoviruses and Rabies', 10, '10. Systematic Virology', 7, '["Measles virus, Rubella virus","Rabies virus, Mumps virus"]'),
  ('microbiology', '10-systematic-virology-coronaviruses', 'Coronaviruses', 10, '10. Systematic Virology', 8, '["SARS-CoV, SARS-CoV-2, MERS-CoV"]'),
  ('microbiology', '10-systematic-virology-viral-haemorrhagic-fevers', 'Viral Haemorrhagic Fevers', 10, '10. Systematic Virology', 9, '["Definition and classification","Yellow fever","Ebola virus, Lassa virus","Dengue virus, Marburg virus, Hantavirus"]'),
  ('microbiology', '10-systematic-virology-human-immunodeficiency-virus-hiv', 'Human Immunodeficiency Virus (HIV)', 10, '10. Systematic Virology', 10, '[]'),
  ('microbiology', '10-systematic-virology-rotavirus-reovirus-calicivirus', 'Rotavirus, Reovirus, Calicivirus', 10, '10. Systematic Virology', 11, '[]'),
  ('microbiology', '11-clinical-syndromes-clinical-syndrome-i', 'Clinical Syndrome I', 11, '11. Clinical Syndromes', 1, '["Pneumonia","Meningitis"]'),
  ('microbiology', '11-clinical-syndromes-clinical-syndrome-ii', 'Clinical Syndrome II', 11, '11. Clinical Syndromes', 2, '["Overview of sexually transmitted infections"]'),
  ('haematology-immunology', 'haematopoiesis-and-red-cell-physiology-introduction-to-haematology', 'Introduction to haematology', 1, 'Haematopoiesis and Red Cell Physiology', 1, '[]'),
  ('haematology-immunology', 'haematopoiesis-and-red-cell-physiology-haematopoiesis-overview', 'Haematopoiesis overview', 1, 'Haematopoiesis and Red Cell Physiology', 2, '[]'),
  ('haematology-immunology', 'haematopoiesis-and-red-cell-physiology-erythropoiesis-and-erythropoietin', 'Erythropoiesis and erythropoietin', 1, 'Haematopoiesis and Red Cell Physiology', 3, '[]'),
  ('haematology-immunology', 'haematopoiesis-and-red-cell-physiology-red-blood-cell-biochemistry', 'Red blood cell biochemistry', 1, 'Haematopoiesis and Red Cell Physiology', 4, '[]'),
  ('haematology-immunology', 'haematopoiesis-and-red-cell-physiology-red-blood-cell-membrane', 'Red blood cell membrane', 1, 'Haematopoiesis and Red Cell Physiology', 5, '[]'),
  ('haematology-immunology', 'haematopoiesis-and-red-cell-physiology-hereditary-spherocytosis', 'Hereditary spherocytosis', 1, 'Haematopoiesis and Red Cell Physiology', 6, '[]'),
  ('haematology-immunology', 'haematopoiesis-and-red-cell-physiology-hereditary-elliptocytosis', 'Hereditary elliptocytosis', 1, 'Haematopoiesis and Red Cell Physiology', 7, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-iron-metabolism', 'Iron metabolism', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 1, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-iron-deficiency-anaemia', 'Iron deficiency anaemia', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 2, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-anaemia-of-chronic-disease', 'Anaemia of chronic disease', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 3, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-iron-overload', 'Iron overload', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 4, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-folate-metabolism', 'Folate metabolism', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 5, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-vitamin-b12-metabolism', 'Vitamin B12 metabolism', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 6, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-megaloblastic-anaemia', 'Megaloblastic anaemia', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 7, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-pernicious-anaemia', 'Pernicious anaemia', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 8, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-investigating-the-anaemias', 'Investigating the anaemias', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 9, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-inherited-haemolytic-anaemias', 'Inherited haemolytic anaemias', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 10, '[]'),
  ('haematology-immunology', 'iron-folate-and-b12-metabolism-anaemias-acquired-haemolytic-anaemias', 'Acquired haemolytic anaemias', 2, 'Iron, Folate and B12 Metabolism / Anaemias', 11, '[]'),
  ('haematology-immunology', 'haemoglobinopathies-haemoglobin-structure-function-and-synthesis', 'Haemoglobin structure, function and synthesis', 3, 'Haemoglobinopathies', 1, '[]'),
  ('haematology-immunology', 'haemoglobinopathies-haemoglobin-variants', 'Haemoglobin variants', 3, 'Haemoglobinopathies', 2, '[]'),
  ('haematology-immunology', 'haemoglobinopathies-sickle-cell-anaemia-i-and-ii', 'Sickle cell anaemia I & II', 3, 'Haemoglobinopathies', 3, '[]'),
  ('haematology-immunology', 'haemoglobinopathies-alpha-thalassaemia', 'Alpha thalassaemia', 3, 'Haemoglobinopathies', 4, '[]'),
  ('haematology-immunology', 'haemoglobinopathies-beta-thalassaemia', 'Beta thalassaemia', 3, 'Haemoglobinopathies', 5, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-thrombopoiesis-and-thrombopoietin', 'Thrombopoiesis and thrombopoietin', 4, 'Platelets and Coagulation', 1, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-platelet-physiology-and-thrombomimetics', 'Platelet physiology and thrombomimetics', 4, 'Platelets and Coagulation', 2, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-thrombocytosis-and-thrombocytopenia', 'Thrombocytosis and thrombocytopenia', 4, 'Platelets and Coagulation', 3, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-physiology-of-coagulation-factors', 'Physiology of coagulation factors', 4, 'Platelets and Coagulation', 4, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-introduction-to-the-coagulation-cascades', 'Introduction to the coagulation cascades', 4, 'Platelets and Coagulation', 5, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-haemophilia-a', 'Haemophilia A', 4, 'Platelets and Coagulation', 6, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-haemophilia-b', 'Haemophilia B', 4, 'Platelets and Coagulation', 7, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-von-willebrand-disease-i-and-ii', 'Von Willebrand disease I & II', 4, 'Platelets and Coagulation', 8, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-venous-thromboembolism', 'Venous thromboembolism', 4, 'Platelets and Coagulation', 9, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-anticoagulation-therapy', 'Anticoagulation therapy', 4, 'Platelets and Coagulation', 10, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-thrombotic-thrombocytopenic-purpura-haemolytic-uraemic-syndrome', 'Thrombotic thrombocytopenic purpura / Haemolytic uraemic syndrome', 4, 'Platelets and Coagulation', 11, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-disseminated-intravascular-coagulation', 'Disseminated intravascular coagulation', 4, 'Platelets and Coagulation', 12, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-inherited-thrombophilias', 'Inherited thrombophilias', 4, 'Platelets and Coagulation', 13, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-acquired-thrombophilias', 'Acquired thrombophilias', 4, 'Platelets and Coagulation', 14, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-liver-disease-and-bleeding-disorder', 'Liver disease and bleeding disorder', 4, 'Platelets and Coagulation', 15, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-immune-thrombocytopenic-purpura', 'Immune thrombocytopenic purpura', 4, 'Platelets and Coagulation', 16, '[]'),
  ('haematology-immunology', 'platelets-and-coagulation-haemorrhagic-disease-of-the-newborn', 'Haemorrhagic disease of the newborn', 4, 'Platelets and Coagulation', 17, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-the-spleen-in-haematology', 'The spleen in haematology', 5, 'Bone Marrow Failure and Myeloid Disorders', 1, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-pancytopenia', 'Pancytopenia', 5, 'Bone Marrow Failure and Myeloid Disorders', 2, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-inherited-bone-marrow-failure-syndromes', 'Inherited bone marrow failure syndromes', 5, 'Bone Marrow Failure and Myeloid Disorders', 3, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-acquired-bone-marrow-failure-syndromes-aplastic', 'Acquired bone marrow failure syndromes: Aplastic anaemia', 5, 'Bone Marrow Failure and Myeloid Disorders', 4, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-paroxysmal-nocturnal-haemoglobinuria', 'Paroxysmal nocturnal haemoglobinuria', 5, 'Bone Marrow Failure and Myeloid Disorders', 5, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-leukaemogenesis-i-and-ii', 'Leukaemogenesis I & II', 5, 'Bone Marrow Failure and Myeloid Disorders', 6, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-acute-myeloid-leukaemia', 'Acute myeloid leukaemia', 5, 'Bone Marrow Failure and Myeloid Disorders', 7, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-chronic-myeloid-leukaemia', 'Chronic myeloid leukaemia', 5, 'Bone Marrow Failure and Myeloid Disorders', 8, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-myelodysplastic-syndrome-mds-i-and-ii', 'Myelodysplastic syndrome (MDS) I & II', 5, 'Bone Marrow Failure and Myeloid Disorders', 9, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-polycythaemia-vera', 'Polycythaemia vera', 5, 'Bone Marrow Failure and Myeloid Disorders', 10, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-essential-thrombocythaemia', 'Essential thrombocythaemia', 5, 'Bone Marrow Failure and Myeloid Disorders', 11, '[]'),
  ('haematology-immunology', 'bone-marrow-failure-and-myeloid-disorders-primary-myelofibrosis', 'Primary myelofibrosis', 5, 'Bone Marrow Failure and Myeloid Disorders', 12, '[]'),
  ('haematology-immunology', 'lymphoid-malignancies-acute-lymphoblastic-leukaemia', 'Acute lymphoblastic leukaemia', 6, 'Lymphoid Malignancies', 1, '[]'),
  ('haematology-immunology', 'lymphoid-malignancies-chronic-lymphocytic-leukaemia-diagnosis-and-treatment', 'Chronic lymphocytic leukaemia (diagnosis and treatment)', 6, 'Lymphoid Malignancies', 2, '[]'),
  ('haematology-immunology', 'lymphoid-malignancies-introduction-to-the-lymphomas', 'Introduction to the lymphomas', 6, 'Lymphoid Malignancies', 3, '[]'),
  ('haematology-immunology', 'lymphoid-malignancies-hodgkins-lymphoma', 'Hodgkin''s lymphoma', 6, 'Lymphoid Malignancies', 4, '[]'),
  ('haematology-immunology', 'lymphoid-malignancies-non-hodgkins-lymphoma', 'Non-Hodgkin''s lymphoma', 6, 'Lymphoid Malignancies', 5, '[]'),
  ('haematology-immunology', 'lymphoid-malignancies-burkitt-lymphoma', 'Burkitt lymphoma', 6, 'Lymphoid Malignancies', 6, '[]'),
  ('haematology-immunology', 'lymphoid-malignancies-multiple-myeloma', 'Multiple myeloma', 6, 'Lymphoid Malignancies', 7, '[]'),
  ('haematology-immunology', 'transfusion-medicine-abo-and-rh-blood-group-systems', 'ABO and Rh blood group systems', 7, 'Transfusion Medicine', 1, '[]'),
  ('haematology-immunology', 'transfusion-medicine-other-blood-group-systems', 'Other blood group systems', 7, 'Transfusion Medicine', 2, '[]'),
  ('haematology-immunology', 'transfusion-medicine-indications-for-blood-transfusion', 'Indications for blood transfusion', 7, 'Transfusion Medicine', 3, '[]'),
  ('haematology-immunology', 'transfusion-medicine-blood-donor-selection', 'Blood donor selection', 7, 'Transfusion Medicine', 4, '[]'),
  ('haematology-immunology', 'transfusion-medicine-autologous-blood-donation-transfusion', 'Autologous blood donation/transfusion', 7, 'Transfusion Medicine', 5, '[]'),
  ('haematology-immunology', 'transfusion-medicine-massive-blood-loss-massive-blood-transfusion', 'Massive blood loss / massive blood transfusion', 7, 'Transfusion Medicine', 6, '[]'),
  ('haematology-immunology', 'transfusion-medicine-complications-of-blood-transfusion', 'Complications of blood transfusion', 7, 'Transfusion Medicine', 7, '[]'),
  ('haematology-immunology', 'transfusion-medicine-blood-component-therapy-and-indications', 'Blood component therapy and indications', 7, 'Transfusion Medicine', 8, '[]'),
  ('haematology-immunology', 'transfusion-medicine-management-of-blood-transfusion-related-reactions', 'Management of blood transfusion-related reactions', 7, 'Transfusion Medicine', 9, '[]'),
  ('haematology-immunology', 'transfusion-medicine-introduction-to-haemovigilance', 'Introduction to haemovigilance', 7, 'Transfusion Medicine', 10, '[]'),
  ('haematology-immunology', 'transfusion-medicine-haemolytic-disease-of-the-newborn-i-and-ii', 'Haemolytic disease of the newborn I & II', 7, 'Transfusion Medicine', 11, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-haematology-in-pregnancy-i-and-ii', 'Haematology in pregnancy I & II', 8, 'Haematology in Special Populations and Clinical Practice', 1, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-haematology-in-neonates-i-and-ii', 'Haematology in neonates I & II', 8, 'Haematology in Special Populations and Clinical Practice', 2, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-haematological-changes-in-systemi', 'Haematological changes in systemic diseases', 8, 'Haematology in Special Populations and Clinical Practice', 3, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-haematology-in-the-elderly', 'Haematology in the elderly', 8, 'Haematology in Special Populations and Clinical Practice', 4, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-haematological-emergencies', 'Haematological emergencies', 8, 'Haematology in Special Populations and Clinical Practice', 5, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-supportive-care-in-haematological', 'Supportive care in haematological malignancies', 8, 'Haematology in Special Populations and Clinical Practice', 6, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-chemotherapy-i-and-ii-haemato-onc', 'Chemotherapy I & II (haemato-oncology)', 8, 'Haematology in Special Populations and Clinical Practice', 7, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-introduction-to-haematopoietic-st', 'Introduction to haematopoietic stem cell transplantation (HSCT)', 8, 'Haematology in Special Populations and Clinical Practice', 8, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-application-of-hsct-in-haematolog', 'Application of HSCT in haematology', 8, 'Haematology in Special Populations and Clinical Practice', 9, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-introduction-to-gene-therapy', 'Introduction to gene therapy', 8, 'Haematology in Special Populations and Clinical Practice', 10, '[]'),
  ('haematology-immunology', 'haematology-in-special-populations-and-clinical-practice-application-of-gene-therapy-in-ha', 'Application of gene therapy in haematology', 8, 'Haematology in Special Populations and Clinical Practice', 11, '[]'),
  ('haematology-immunology', 'basic-immunology-introduction-to-immunology', 'Introduction to immunology', 9, 'Basic Immunology', 1, '[]'),
  ('haematology-immunology', 'basic-immunology-innate-immunity-i-and-ii', 'Innate immunity I & II', 9, 'Basic Immunology', 2, '[]'),
  ('haematology-immunology', 'basic-immunology-tolerance-immune-paralysis-and-autoimmunity', 'Tolerance, immune paralysis and autoimmunity', 9, 'Basic Immunology', 3, '[]'),
  ('haematology-immunology', 'basic-immunology-the-lymphoid-system-lymphoid-organs', 'The lymphoid system / lymphoid organs', 9, 'Basic Immunology', 4, '[]'),
  ('haematology-immunology', 'basic-immunology-lymphopoiesis-and-plasma-cell-development', 'Lymphopoiesis and plasma cell development', 9, 'Basic Immunology', 5, '[]'),
  ('haematology-immunology', 'basic-immunology-antibody-production', 'Antibody production', 9, 'Basic Immunology', 6, '[]'),
  ('haematology-immunology', 'basic-immunology-antigens-and-immune-response-antigenic-determinants-factors-affecting-imm', 'Antigens and immune response: antigenic determinants, factors affecting immune response, fate of antigens', 9, 'Basic Immunology', 7, '[]'),
  ('haematology-immunology', 'basic-immunology-tumour-antigens', 'Tumour antigens', 9, 'Basic Immunology', 8, '[]'),
  ('haematology-immunology', 'basic-immunology-complement-system-i-and-ii', 'Complement system I & II', 9, 'Basic Immunology', 9, '[]'),
  ('haematology-immunology', 'basic-immunology-immunoglobulin-synthesis', 'Immunoglobulin synthesis', 9, 'Basic Immunology', 10, '[]'),
  ('haematology-immunology', 'basic-immunology-immune-tolerance', 'Immune tolerance', 9, 'Basic Immunology', 11, '[]'),
  ('haematology-immunology', 'basic-immunology-hla-i-and-ii', 'HLA I & II', 9, 'Basic Immunology', 12, '[]'),
  ('haematology-immunology', 'immune-dysregulation-and-clinical-immunology-immunosuppression-i-and-ii', 'Immunosuppression I & II', 10, 'Immune Dysregulation and Clinical Immunology', 1, '[]'),
  ('haematology-immunology', 'immune-dysregulation-and-clinical-immunology-immunology-of-immunodeficiency-i-and-ii', 'Immunology of immunodeficiency I & II', 10, 'Immune Dysregulation and Clinical Immunology', 2, '[]'),
  ('haematology-immunology', 'immune-dysregulation-and-clinical-immunology-autoimmune-disease-i-and-ii', 'Autoimmune disease I & II', 10, 'Immune Dysregulation and Clinical Immunology', 3, '[]'),
  ('haematology-immunology', 'immune-dysregulation-and-clinical-immunology-autoimmune-disorders-with-haematological-invo', 'Autoimmune disorders with haematological involvement', 10, 'Immune Dysregulation and Clinical Immunology', 4, '[]'),
  ('haematology-immunology', 'immune-dysregulation-and-clinical-immunology-immune-haemolytic-anaemias', 'Immune haemolytic anaemias', 10, 'Immune Dysregulation and Clinical Immunology', 5, '[]'),
  ('haematology-immunology', 'immune-dysregulation-and-clinical-immunology-immunoproliferative-disorders', 'Immunoproliferative disorders', 10, 'Immune Dysregulation and Clinical Immunology', 6, '[]'),
  ('haematology-immunology', 'immune-dysregulation-and-clinical-immunology-immunology-of-organ-transplant-i-and-ii', 'Immunology of organ transplant I & II', 10, 'Immune Dysregulation and Clinical Immunology', 7, '[]'),
  ('haematology-immunology', 'immune-dysregulation-and-clinical-immunology-immunology-of-malnutrition-i-and-ii', 'Immunology of malnutrition I & II', 10, 'Immune Dysregulation and Clinical Immunology', 8, '[]'),
  ('haematology-immunology', 'immune-dysregulation-and-clinical-immunology-immunology-of-tropical-parasitic-fungal-viral', 'Immunology of tropical parasitic, fungal, viral and bacterial diseases', 10, 'Immune Dysregulation and Clinical Immunology', 9, '[]'),
  ('haematology-immunology', 'immune-dysregulation-and-clinical-immunology-human-immunodeficiency-virus-hiv-i-and-ii', 'Human Immunodeficiency Virus (HIV) I & II', 10, 'Immune Dysregulation and Clinical Immunology', 10, '[]')
) as seed(course_slug, slug, title, day_number, day_title, order_index, subtopics)
  on seed.course_slug = c.slug;

commit;
